### ISSUE TITLE
add redis 

### ISSUE THREAD

**Issue by Mambix** [Mambix/rancher-catalog#1]
```YAML
version: '2'
services:
  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      REDIS_PASSWORD: changeme!
      REDIS_MAXMEMORY_POLICY: allkeys-lru
      REDIS_MAXMEMORY: 4G
    stdin_open: true
    network_mode: host
    tty: true
    ports:
    - 6379:6379/tcp
    labels:
      io.rancher.container.pull_image: always
```

```YAML
version: '2'
services:
  neo4j:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
```
